services:
  postgres:
    image:  postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/mydb?schema=sample
    depends_on:
      - postgres

volumes:
  db_data:
    