name: continuous_deployment

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning the code
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: abhiifour/first-app:${{ github.sha }}
    
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 51.21.134.200
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
        script: |
          echo "inside vm"
          sudo docker stop first-app && sudo docker run -d -p 3000:3000 abhiifour/first-app:${{ github.sha }}